### ISSUE TITLE
Tell renovate about browserless tag in values.yaml

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#2720] opened 2022-05-12 12:47 UTC
Follow-up to #2656

We should tell renovate about the browserless docker image version specified here: https://github.com/ecamp/ecamp3/blob/devel/.helm/ecamp3/values.yaml#L82

It's a little tricky, because "1.53-puppeteer-13.6.0" contains two separate versions.

By default, renovate will treat `1.50.0` as the version and `puppeteer-12.0.1` as the "compatibility" or platform (like "alpine"). It will never update the "compatibility" value, only the version. See https://docs.renovatebot.com/modules/versioning/#docker-versioning

We probably want to update both. So I think we'd need a normal "docker" manager which updates the 1.50.0 part and considers 12.0.1 as fixed, and then additionally a regex manager which updates the 12.0.1 part and considers the 1.50.0 part as fixed.

**Comment by BacLuc** [comment] 2023-02-14 09:20
Duplicate of #3120?

**Closed as completed** 2023-02-26 09:15 UTC
