### ISSUE TITLE
E-Component support vee-mode -> passed to ValidationProvide

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#3077] opened 2022-10-09 13:34 UTC
e.g. vee-mode='passiv' on Login-Screen

**Comment by carlobeltrame** [comment] 2022-10-09 16:25
Duplicate of #3023?

**Comment by pmattmann** [comment] 2022-10-14 09:07
On Logon-Screen fixed by #3084

**Closed as completed** 2024-04-27 12:55 UTC
