### ISSUE TITLE
Clarify moveScheduleEntries in period edit

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#2294] opened 2021-11-26 17:42 UTC
Show both animations at the same time, to demonstrate the two different ways of functioning.
Use radio buttons with text: "Move schedule entries with time period" & "Only move the time period".

**Comment by usu** [comment] 2022-10-01 14:57
Duplicate of #2468

**Closed as completed by usu** 2022-10-01 14:57 UTC
Labels: type: Frontend, Good first issue, UX/UI
