### ISSUE TITLE
Quantity value check when adding new object to material list

### ISSUE THREAD

**Issue by Zediwan** [ecamp/ecamp3#5081] opened 2024-04-29 08:26 UTC
When trying to add a new object to the material list of a "block" it is possible to enter values other than float but when trying to save then the error is displayed.
I think it would make sense to check for the type of input when the user is finished entering the value then displaying a warning and not just when saving the object.

<img width="605" alt="image" src="https://github.com/ecamp/ecamp3/assets/107117424/df4c78c2-7eb7-4aef-868d-9bd2ab3ede6e">

<img width="1218" alt="image" src="https://github.com/ecamp/ecamp3/assets/107117424/3a02c46d-3bde-467b-b6cb-34d65cefad3f">

**Comment by carlobeltrame** [comment] 2024-04-29 10:04
Thanks for reporting! This is a duplicate of #4729, should be fixed with #5017. If you want to help us out, you can test whether it's really fixed on https://dev.ecamp3.ch

If it's working, the fix should be live on production with the next prod deployment (usually every few months, but the [next one](https://github.com/ecamp/ecamp3/pull/5080) should be soon)

**Comment by pmattmann** [comment] 2024-05-04 17:22
fixed by #5017

**Closed as completed by pmattmann** 2024-05-04 17:22 UTC
