### ISSUE TITLE
Creating a category returns error 500

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#3662] opened 2023-08-03 22:04 UTC
https://ecamp.sentry.io/issues/4368820213/?project=5912620&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

Error happened on dev, did not test on staging, prod or local yet

**Comment by BacLuc** [comment] 2023-08-05 08:51
Trying to reproduce:
1. Tested on prod: :ok: 
2. Tested locally: :ok: 
3. Tested locally against dev database: :ok: 
4. Tested on newly deployed feature branch: :x: 
5. Tested locally against prod image (with some hacks) :x: 

Seems to be https://github.com/doctrine-extensions/DoctrineExtensions/issues/2600
There is the PR: https://github.com/doctrine-extensions/DoctrineExtensions/pull/2651

-> there seems a problem when the code is optimized for production

**Comment by BacLuc** [comment] 2023-08-14 14:35
#3667 is merged now, so it's safe to release.
Hopefully we can revert #3667 again as soon as https://github.com/doctrine-extensions/DoctrineExtensions/pull/2651 is released

**Closed as completed** 2023-09-12 19:31 UTC
Labels: Bug
