### ISSUE TITLE
Switch day in Activity sidebar

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#4189] opened 2023-12-02 13:39 UTC
When i write an activity, i want to be able to quickly look something up in another activity.
This is possible for activities on the same day, but not for activities on other days.

As a Manager or a J+S Coach, i want to be able to go through all activities without switching back to the picasso
or the dashboard.

**Comment by manuelmeister** [comment] 2023-12-02 13:40
Duplicate of #3963

**Closed as not planned by manuelmeister** 2023-12-02 13:40 UTC
Labels: type: Frontend, Needs prototype
