### ISSUE TITLE
Bug: credentials invalid after changing email address

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#3299] opened 2023-02-25 13:01 UTC
After changing the email address and clicking the confirmation link in the email, the credentials turn invalid.

1. In the fronten go to /profile and change email address
2. click confirmation link in email
3. Close message, frontend seems to still be signed in
4. Try to change any value (e.g. first name), fails with "Invalid credentials"

Possible solutions
A. Logout of frontend after successfully finalizing the change email address
B. Or: Automatically issue new JWT after finalizing the email address

**Comment by BacLuc** [comment] 2023-12-02 12:59
Duplicate of #3521

**Closed as completed by BacLuc** 2023-12-02 12:59 UTC
Labels: Bug
